In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
filename='/content/drive/MyDrive/Lab5/data.txt'
raw_text=open(filename,'r',encoding='utf=8').read()
raw_text=raw_text.lower() #convert all char s in to simple letters

In [ ]:
print(raw_text[0:1000])

project gutenberg's alice's adventures in wonderland, by lewis carroll

this ebook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  you may copy it, give it away or
re-use it under the terms of the project gutenberg license included
with this ebook or online at www.gutenberg.org


title: alice's adventures in wonderland

author: lewis carroll

posting date: june 25, 2008 [ebook #11]
release date: march, 1994
[last updated: december 20, 2011]

language: english


*** start of this project gutenberg ebook alice's adventures in wonderland ***










alice's adventures in wonderland

lewis carroll

the millennium fulcrum edition 3.0




chapter i. down the rabbit-hole

alice was beginning to get very tired of sitting by her sister on the
bank, and of having nothing to do: once or twice she had peeped into the
book her sister was reading, but it had no pictures or conversations in
it, 'and what is the use of a book,' thought alice 'without picture

In [ ]:
chars=sorted(list(set(raw_text)))
print(chars)
#create mapping

char_to_int = dict((c,i)for i ,c in enumerate(chars)) #crerate a dictonary called char_to_int


['\n', ' ', '!', '"', '#', '$', '%', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', '@', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [ ]:
len(chars)   #no of unique characters  =58

58

In [ ]:
#create mapping

char_to_int = dict((c,i)for i ,c in enumerate(chars)) #crerate a dictonary called char_to_int


In [ ]:
char_to_int

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '#': 4,
 '$': 5,
 '%': 6,
 "'": 7,
 '(': 8,
 ')': 9,
 '*': 10,
 ',': 11,
 '-': 12,
 '.': 13,
 '/': 14,
 '0': 15,
 '1': 16,
 '2': 17,
 '3': 18,
 '4': 19,
 '5': 20,
 '6': 21,
 '7': 22,
 '8': 23,
 '9': 24,
 ':': 25,
 ';': 26,
 '?': 27,
 '@': 28,
 '[': 29,
 ']': 30,
 '_': 31,
 'a': 32,
 'b': 33,
 'c': 34,
 'd': 35,
 'e': 36,
 'f': 37,
 'g': 38,
 'h': 39,
 'i': 40,
 'j': 41,
 'k': 42,
 'l': 43,
 'm': 44,
 'n': 45,
 'o': 46,
 'p': 47,
 'q': 48,
 'r': 49,
 's': 50,
 't': 51,
 'u': 52,
 'v': 53,
 'w': 54,
 'x': 55,
 'y': 56,
 'z': 57}

In [ ]:
#Getting the details of the dataset
n_chars=len(raw_text)
n_vocab=len(chars)
print("Total characters:", n_chars)
print("Total vocabs:", n_vocab)


Total characters: 163780
Total vocabs: 58


In [ ]:
#Prepare the dataset of input to output pairs encoded as integers

seq_length = 15
dataX=[]
dataY=[]  #character that have the 16th possition
for i in range(0,n_chars-seq_length, 1):

  seq_in = raw_text[i:i + seq_length]
 # print(seq_in) #this is input
  seq_out = raw_text[i + seq_length]
  #print("this is output")
  dataX.append([char_to_int[char] for char in seq_in])
  dataY.append(char_to_int[seq_out]) #character that can be have in the 16th possition
n_patterns = len(dataY)
print("Total Patterns: " , n_patterns)
 #assign values for each characters as input and they giva a output for that by their own by predicting
  #characters will be assgined by ceratain numbers

Total Patterns:  163765


In [ ]:
dataX

[[47, 49, 46, 41, 36, 34, 51, 1, 38, 52, 51, 36, 45, 33, 36],
 [49, 46, 41, 36, 34, 51, 1, 38, 52, 51, 36, 45, 33, 36, 49],
 [46, 41, 36, 34, 51, 1, 38, 52, 51, 36, 45, 33, 36, 49, 38],
 [41, 36, 34, 51, 1, 38, 52, 51, 36, 45, 33, 36, 49, 38, 7],
 [36, 34, 51, 1, 38, 52, 51, 36, 45, 33, 36, 49, 38, 7, 50],
 [34, 51, 1, 38, 52, 51, 36, 45, 33, 36, 49, 38, 7, 50, 1],
 [51, 1, 38, 52, 51, 36, 45, 33, 36, 49, 38, 7, 50, 1, 32],
 [1, 38, 52, 51, 36, 45, 33, 36, 49, 38, 7, 50, 1, 32, 43],
 [38, 52, 51, 36, 45, 33, 36, 49, 38, 7, 50, 1, 32, 43, 40],
 [52, 51, 36, 45, 33, 36, 49, 38, 7, 50, 1, 32, 43, 40, 34],
 [51, 36, 45, 33, 36, 49, 38, 7, 50, 1, 32, 43, 40, 34, 36],
 [36, 45, 33, 36, 49, 38, 7, 50, 1, 32, 43, 40, 34, 36, 7],
 [45, 33, 36, 49, 38, 7, 50, 1, 32, 43, 40, 34, 36, 7, 50],
 [33, 36, 49, 38, 7, 50, 1, 32, 43, 40, 34, 36, 7, 50, 1],
 [36, 49, 38, 7, 50, 1, 32, 43, 40, 34, 36, 7, 50, 1, 32],
 [49, 38, 7, 50, 1, 32, 43, 40, 34, 36, 7, 50, 1, 32, 35],
 [38, 7, 50, 1, 32, 43, 40, 34, 

In [ ]:
#Pre Processing task
import numpy as np
X = np.reshape(dataX, (n_patterns, seq_length, 1) )

X = X/ float(n_vocab)
print(X)

#pre processing task


#X = numpy.reshape(dataX, (n_patterns, seq_length, 1))

#rescalling to make it easier to train the model , resclae thevalues  to between 0 and 1
#X= X / float(n_vocab)
#print(X)

#scalling between 0 and 1 beacuse that is the format LSRTM models get the values

[[[0.81034483]
  [0.84482759]
  [0.79310345]
  ...
  [0.77586207]
  [0.56896552]
  [0.62068966]]

 [[0.84482759]
  [0.79310345]
  [0.70689655]
  ...
  [0.56896552]
  [0.62068966]
  [0.84482759]]

 [[0.79310345]
  [0.70689655]
  [0.62068966]
  ...
  [0.62068966]
  [0.84482759]
  [0.65517241]]

 ...

 [[0.55172414]
  [0.56896552]
  [0.79310345]
  ...
  [0.79310345]
  [0.79310345]
  [0.72413793]]

 [[0.56896552]
  [0.79310345]
  [0.89655172]
  ...
  [0.79310345]
  [0.72413793]
  [0.86206897]]

 [[0.79310345]
  [0.89655172]
  [0.87931034]
  ...
  [0.72413793]
  [0.86206897]
  [0.22413793]]]


In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras.utils import np_utils

y = np_utils.to_categorical(dataY)



In [ ]:
from keras.layers.attention.multi_head_attention import activation
from keras.api._v2.keras import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import ModelCheckpoint

In [ ]:
n_vocab

58

In [ ]:
#dataY

In [ ]:
 y = np_utils.to_categorical(dataY)


In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
from keras.layers.attention.multi_head_attention import activation
from keras.api._v2.keras import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import ModelCheckpoint

In [ ]:
from keras.engine.sequential import Sequential
#define the LSTM model

model = Sequential()
model.add(LSTM(256, input_shape=(X.shape[1], X.shape[2])))
model.add(Dropout(0.2)) #overcome the overfitting
model.add(Dense(y.shape[1], activation = 'softmax')) #softmax wil provide probabilities for each character
model.compile(loss='categorical_crossentropy' , optimizer = 'adam') #categorical crossentropy since we have multiple  classes

#define the checkpoints
filepath ="weights-improvement-{epoch:02d}--{loss:.4f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='loss' , verbose=1, save_best_only=True, mode='min')
callbacks_list = [checkpoint]

In [ ]:
epochs = 10
batch_size = 128

In [ ]:
model.fit(X, y , epochs = epochs, batch_size=batch_size, callbacks=callbacks_list)

Epoch 1/10
1280/1280 [==============================] - ETA: 0s - loss: 2.9778
Epoch 1: loss improved from inf to 2.97777, saving model to weights-improvement-01--2.9778.hdf5
1280/1280 [==============================] - 137s 105ms/step - loss: 2.9778
Epoch 2/10
1280/1280 [==============================] - ETA: 0s - loss: 2.7970
Epoch 2: loss improved from 2.97777 to 2.79701, saving model to weights-improvement-02--2.7970.hdf5
1280/1280 [==============================] - 136s 106ms/step - loss: 2.7970
Epoch 3/10
1280/1280 [==============================] - ETA: 0s - loss: 2.7186
Epoch 3: loss improved from 2.79701 to 2.71862, saving model to weights-improvement-03--2.7186.hdf5
1280/1280 [==============================] - 136s 106ms/step - loss: 2.7186
Epoch 4/10
1280/1280 [==============================] - ETA: 0s - loss: 2.6669
Epoch 4: loss improved from 2.71862 to 2.66687, saving model to weights-improvement-04--2.6669.hdf5
1280/1280 [==============================] - 131s 102ms/step

In [ ]:

filename = "weights-improvement-10--2.4056.hdf5"
model.load_weights(filename)
model.compile(loss ='categorical_crossentropy', optimizer='adam')

In [ ]:
int_to_char = {i: char for i, char in enumerate(chars)}

In [ ]:
print(len(dataX))
start = numpy.random.randint(0, len(dataX)-1)
print(start)
pattern = dataX[start] #dataX contains list of patterns
print("Seed:")
print("\"",''.join([int_to_char[value] for value in pattern]), "\"")


#seed is the 15 size of word phrase that randomly predictedbythe model for us

163765
187
Seed:
" t, give it away "


In [ ]:
#letters that can be predict after the away word
length =10 #run in 10 times
final = [] #give the 10 values as that predicted as a list


 #using a for loop one by 1 predict the values just after thwe 15
for i in range(length):
  x = numpy.reshape(pattern, (1, len(pattern), 1))  #take the pattern random
  x = x / float(n_vocab)

  prediction = model.predict(x, verbose =0)

  index = numpy.argmax(prediction)

  result = int_to_char[index]

  final.append(result)

  pattern.append(index)

  pattern = pattern[1:len(pattern)]
print(final)

[' ', 't', 'o', ' ', 't', 'h', 'e', ' ', 't', 'o']
